[workspace]
members = [
    "xrcad_lib",
    "xrcad_app"
]

resolver = "3"

[workspace.dependencies]
nalgebra = "0.32"
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", features = ["wayland"] }
bevy_egui = "*"

