[package]
name = "xrcad_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = { workspace = true }
bevy = { workspace = true }
bevy_mod_openxr = { version = "0.3.0", optional = true }

[features]
openxr = ["bevy_mod_openxr"]
default = []