[package]
name = "xrcad_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "xrcad_lib"
# Default crate type is rlib, which works for most cases
crate-type = ["rlib"]

[dependencies]
nalgebra = { workspace = true }
bevy = { workspace = true }
