[package]
name = "xrcad_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[target.'cfg(target_os = "android")'.lib]
crate-type = ["cdylib"]

[dependencies]
nalgebra = { workspace = true }
bevy = { workspace = true }
