[package]
name = "xrcad_app"
version = "0.1.0"
edition = "2024"

[dependencies]
xrcad_lib = { path = "../xrcad_lib" }
nalgebra = { workspace = true }
bevy = { workspace = true }
bevy_mod_openxr = { version = "0.3.0", optional = true }

[features]
openxr = ["bevy_mod_openxr"]
default = []
