[package]
name = "xrcad_app"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
nalgebra = { workspace = true }
xrcad_lib = { path = "../xrcad_lib" }
bevy_egui = { workspace = true }
