name: Build Bevy App
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
        exclude:
          - os: windows-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Build Native
        run: cargo build --release --target ${{ matrix.target }}

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          script: |
            echo "Emulator is up"
            adb devices
      - name: Wait for Android emulator to boot
        run: |
          adb wait-for-device
          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            echo "Waiting for emulator to start..."
            sleep 5
          done
          echo "Emulator booted"
      - name: Add Rust Android target
        run: rustup target add aarch64-linux-android
      - name: Install cargo-ndk
        run: cargo install cargo-ndk
      - name: Build for Android
        run: cargo ndk -t arm64-v8a -o ./apk build --release
