name: Build Bevy App
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
        exclude:
          - os: windows-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Install ALSA and Wayland dev libraries
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev pkg-config libwayland-dev libxkbcommon-dev
      - name: Build Native
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: xrcad-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/xrcad*

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Android target
        run: rustup target add aarch64-linux-android

      - name: Install cargo-apk
        run: cargo install cargo-apk cargo-ndk

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK Platform 30
        run: sdkmanager "platforms;android-30"

      - name: Build APK with cargo-apk
        run: cargo apk build --release
        working-directory: xrcad_app

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: xrcadd_app/target/android-artifacts/**/*.apk
