name: Build Bevy App
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev pkg-config libwayland-dev libxkbcommon-dev
      - run: cargo build --release --target x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v4
        with:
          name: xrcad-linux
          path: target/x86_64-unknown-linux-gnu/release/xrcad_app # or your binary name

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add aarch64-linux-android
      - run: cargo install cargo-apk cargo-ndk
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - run: sdkmanager "platforms;android-30"
      - run: cargo apk build --release
        working-directory: xrcad_app
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: xrcad_app/target/android-artifacts/**/*.apk
