
name: Build Bevy App
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: |
            x86_64-unknown-linux-gnu
            x86_64-pc-windows-gnu
      - name: Build Native
        run: cargo build --release

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
      - name: Install cargo-ndk
        run: cargo install cargo-ndk
      - name: Build for Android
        run: cargo ndk -t arm64-v8a -o ./apk build --release

